import { typeWithParameters } from '@angular/compiler/src/render3/util';
import { Component, OnInit } from '@angular/core';
import { SmcService } from '../smc.service';
import { default as Web3} from 'web3';
import { ChartDataSets, ChartOptions } from 'chart.js';
import { Color, Label } from 'ng2-charts';


@Component({
  selector: 'app-panelowner',
  templateUrl: './panelowner.component.html',
  styleUrls: ['./panelowner.component.css']
})
export class PanelownerComponent implements OnInit {
  private web3:Web3;
  elecgenerated = false;
  public panel = {ownerAddr:"",panelid:""};


  public lineChartData: ChartDataSets[] = [
    { data: [5, 5, 5 , 5, 5, 5, 5], label: 'Electricity Generated by My Solar Panel' },
  ];
  public lineChartData2: ChartDataSets[] = [
    { data: [65, 59, 80, 81, 56, 55, 40], label: 'Electricity Generated by My Solar Panel' },
  ];
  public lineChartLabels: Label[] = ['January', 'February', 'March', 'April', 'May', 'June', 'July'];
  public lineChartOptions: (ChartOptions & { annotation: any }) = {
    annotation: true,
    responsive: true,
  };
  public lineChartColors: Color[] = [
    {
      borderColor: 'black',
      backgroundColor: 'rgba(137, 196, 244, 0.3)',
    },
  ];
  public lineChartLegend = true;
  public lineChartType = 'line';
  public lineChartPlugins = [];


  constructor(private _smcService:SmcService) { }

  ngOnInit(){
  }

  onElecGen(){
    
  }

}

//0x01264f571e048c93Dd2A9A04d7FB040255B4e229 (100 ETH)
//0xC5B30fc89197418F02fC5b8A6603e3e44aE5c3Df
// mypanel.regNo,
//       mypanel.manufct,
//       mypanel.manufctAddr,
//       mypanel.ownerAddr,

//  onRegisterPanel(mypanel){
//   if(mypanel){
//     this._smcService.addPanel(mypanel).then(() =>{
//       this.mypanel={};
//     });
//   }
// }